services:
  kcc:
    image: ghcr.io/mcarr823/auto-kcc:amd64
    #image: ghcr.io/mcarr823/auto-kcc:arm64
    volumes:
      #- ./kindlegen:/app/kindlegen:ro
      - ./input:/input
      - ./output:/output
      - ./failed:/failed
    environment:
      STRETCH: 'true'
      UPSCALE: 'true'
      #DELETE: 'true'
      PROFILE: 'KoL'